// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSU0hOm_uvorNCw2Hzh_WDctsYuGIeM1c',
    appId: '1:1050414492138:web:c76cfdaf418522eb4e6a93',
    messagingSenderId: '1050414492138',
    projectId: 'macidp-fd534',
    authDomain: 'macidp-fd534.firebaseapp.com',
    storageBucket: 'macidp-fd534.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0L0VDhM6nISAqNMjEC92puqoNjrshj8',
    appId: '1:1050414492138:android:f4f33cc0ea4e0ec54e6a93',
    messagingSenderId: '1050414492138',
    projectId: 'macidp-fd534',
    storageBucket: 'macidp-fd534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkM9iRDkNlr7sBBYhnkQjZPWqymRDpjzU',
    appId: '1:1050414492138:ios:a712d31ff6bd02934e6a93',
    messagingSenderId: '1050414492138',
    projectId: 'macidp-fd534',
    storageBucket: 'macidp-fd534.appspot.com',
    iosBundleId: 'com.macidp.app.macidp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkM9iRDkNlr7sBBYhnkQjZPWqymRDpjzU',
    appId: '1:1050414492138:ios:da99f62673fc74ea4e6a93',
    messagingSenderId: '1050414492138',
    projectId: 'macidp-fd534',
    storageBucket: 'macidp-fd534.appspot.com',
    iosBundleId: 'com.macidp.app.macidp.RunnerTests',
  );
}
